# Generated by Django 4.1.1 on 2022-10-05 01:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0006_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='secondPhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
