# Generated by Django 4.1.1 on 2022-10-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0007_proveedor_secondphonenumber_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='secondPhoneNumber',
        ),
    ]
